
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: koronet
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1"]
      interval: 1s
      timeout: 10s
      retries: 5
  webapp:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: "redis:6379"
      MYSQL_HOST: "mysql"
    depends_on:
      - redis
      - mysql 
    